trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubUser: $(Docker_username) 
  dockerHubPassword: $(Docker_pass)
  IMAGE_NAME: 'geojit'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        repository: safuvanh/$(IMAGE_NAME)
        tags: |
          latest

    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: login
        containerRegistry: dockerhub  
        username: $(dockerHubUser)
        password: $(dockerHubPassword)

    
    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        command: push
        repository: safuvanh/$(IMAGE_NAME)
        tags: |
          latest

- stage: Deployment
  displayName: Deploy App
  jobs:
  - deployment: deploymentJob
    displayName: Deploying
    environment: 
      name: localhost
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Running Docker container.."
              docker run -d -p 80:8080 safuvanh/$(IMAGE_NAME):latest
            displayName: 'Run Docker Container'